server:
    port: 8768

eureka:
    client:
        healthcheck: true 
        fetch-registry: true

        serviceUrl:
            defaultZone: http://13.209.76.2:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true

