spring:
    application:
        name: story-service
    
    jpa: 
      hibernate:
        ddl-auto: update
        show_sql: true
        use_sql_comments: true
        fotmat_sql: true
        
    datasource:
      url: jdbc:mysql://{Your-MySQL-Server-Address}:3306/story
      username: {MySQL-ID}
      password: {MySQL-PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 2
         

server:
    port: 8768

eureka:
    client:
        healthcheck: true 
        fetch-registry: true

        serviceUrl:
            defaultZone: http://{Your-Eukeka-Server-Address}:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true




